## Configuration file
## Define endpoints and optional parameters
## How to use:
  ## Uncomment the desired block (all lines marked with a single #)
  ## Edit optional parameters accordingly

## See the following link for parameter definitions
## https://www.ncdc.noaa.gov/cdo-web/webservices/v2#gettingstarted

---
endpoints:

## -----------------
#- endpoint: 'datasets'
#- datatypeid: ''              # ACMH
#- locationid: ''              # FIPS:37
#- stationid: ''               # COOP:010957
#- startdate: ''               # 1970-10-03
#- enddate: ''                 # 2012-09-10
#- sortfield: ''               # name
#- sortorder: ''            # desc (default is asc)
#- limit: ''                 # 42
#- offset: ''                 # 24

## -----------------
#- endpoint: 'datacategories'
#- datasetid: 'NEXRAD2'               # GCOM
#- locationid: ''              # FIPS:37
#- stationid: ''               # COOP:010957
#- startdate: ''               # 1970-10-03
#- enddate: ''                 # 2012-09-10
#- sortfield: ''               # name
#- sortorder: ''            # desc (default is asc)
#- limit: ''                 # 42
#- offset: ''                 # 24

## -----------------
#- endpoint: 'datatypes'
#- datasetid: ''               # GCOM
#- locationid: ''              # FIPS:37
#- stationid: ''               # COOP:010957
#- datacategoryid: ''          # TEMP
#- startdate: ''               # 1970-10-03
#- enddate: ''                 # 2012-09-10
#- sortfield: ''               # name
#- sortorder: ''            # desc (default is asc)
#- limit: ''                 # 42
#- offset: ''                 # 24

## -----------------
#- endpoint: 'locationcategories'
#- datasetid: ''               # GCOM
#- startdate: ''               # 1970-10-03
#- enddate: ''                 # 2012-09-10
#- sortfield: ''               # name
#- sortorder: ''            # desc (default is asc)
#- limit: ''                 # 42
#- offset: ''                 # 24

## -----------------
#- endpoint: 'locations'
#- datasetid: ''               # GCOM
#- locationcategoryid: ''      # CITY
#- datacategoryid: ''          # TEMP
#- startdate: ''               # 1970-10-03
#- enddate: ''                 # 2012-09-10
#- sortfield: ''               # name
#- sortorder: ''            # desc (default is asc)
#- limit: ''                 # 42
#- offset: ''                 # 24

## -----------------
#- endpoint: 'stations'
#- datasetid: ''               # GCOM
#- locationid: ''              # FIPS:37
#- datacategoryid: ''          # TEMP
#- datatypeid: ''              # ACMH
#- extent1: ''                 # 47.50
#- extent2: ''                 # -122.5
#- extent3: ''                 # 47.60
#- extent4: ''                 # -121.5
#- startdate: ''               # 1970-10-03
#- enddate: ''                 # 2012-09-10
#- sortfield: ''               # name
#- sortorder: ''            # desc (default is asc)
#- limit: ''                 # 42
#- offset: ''                 # 24

## -----------------
- endpoint: 'data'
- datasetid: 'GSOM'               # GSOM
- datatypeid: ''              # ACMH
- locationid: 'ZIP:28801'              # FIPS:37
- stationid: ''               # COOP:010957
- startdate: '2010-05-01'               # 1970-10-03
- enddate: '2010-05-01'                 # 2012-09-10
- units: ''                   # metric
- sortfield: ''               # name
- sortorder: ''            # desc (default is asc)
- limit: ''                 # 42
- offset: ''                 # 24
- includemetadata: ''     # false
